### ISSUE TITLE
Authentication workflow

### ISSUE THREAD

**Issue by Mackey22** [HumanCellAtlas/data-store-cli#27]
Here is my proposal for where the application will find Authentication credentials. The application will look through an ordered list of places. The first place it finds an access token or credentials in any one of them it will use that.

1. Accept a token in the python bindings. If kwarg `access_token` is set, that token will be passed in the authorization header.
2. Check config files. I plan on using tweak (https://github.com/kislyuk/tweak) to check first `/etc/hca/config.json`, then `~/.config/hca/config.json`, then a config file pointed to from `$HCA_CONFIG_FILE` for variables `access_token` and `refresh_token`.
3. If the user is using a teletype, popup a browser for the user to sign in and give access to email scope. The access token and refresh token will be saved by tweak. 
4. If none of the above work, raise an exception telling the user how to save their access_token and refresh_token to the config files.

**Comment by Mackey22** [comment]
@kislyuk how's this look to you?

**Comment by kislyuk** [comment]
Sounds good 👍 
The user is not really using a teletype :) tty stands for teletype but nowadays people pronounce it "terminal" :)
![image](https://user-images.githubusercontent.com/862013/29101399-d24060f2-7c66-11e7-9bc5-4925bf7aba79.png)

**Comment by Mackey22** [comment]
Like we talked about, a lot of this logic should be in a login command. I'm going to have a login command that will take

**Comment by Mackey22** [comment]
https://github.com/HumanCellAtlas/data-store-cli/pull/29
