### ISSUE TITLE
hca sets logger level to INFO causing noise from other packages

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/data-store-cli#43]
The hca package sets log level to INFO which makes other packages, particularly boto3, fairly chatty.  This makes for a poor UX when the hca package is used in CLI tools trying to output information to their user.
```
cat > test_hca.py << EOF
import hca
import boto3
s3 = boto3.resource('s3')
EOF
python test_hca.py
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
```

**Comment by ttung** [comment]
I don't see this.  Looks like @Mackey22 resolved this.

**Comment by ttung** [comment]
The upload/download APIs are quite chatty and write a lot to stderr.  I will fix that.
